### ISSUE TITLE
BUG-000084758  In the Information Service application  template in ArcGIS Online, the template  configuration page opens with an error.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/utilities-telecom-desktop-addins#9]
<div><div>
<span><b>Salesforce ID:</b> BUG-000084758</span><br/>
<span><b>Salesforce Submitter:</b> Brenda McLuskie</span><br/>
<span><b>Salesforce Submit Date:</b> 1/23/2015 1:35 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Salesforce Attachments:</b> error1.jpg</span><br/>
<span><b>Salesforce Attachments Location:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000084758</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000084758</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Utilities and Telecom</span><br/>
<span><b>Functional Category:</b> ArcGIS for Utilities and Telecom</span><br/>
<span><b>Client Platform:</b> Windows 2012 64 Bit</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Planned fix for next release of ArcGIS Online</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
@MikeMillerGIS @gelisajoseph  can this issue be closed? 

I am trying to clean out all the open support BUG's and ENH's so I can shut down the support connection to this repo and link back to devtopia.

**Comment by MikeMillerGIS** [comment]
app is retired, yes
